CONTRIBUTORS.md
Issue: 1
Added my name in contributors' list and created an account on PhotoStore
=> Added myself in Contributors.md

CONTRIBUTORS.md
=> Added My Username

CONTRIBUTORS.md
Issue: 1
Logged in to PhotoStore website and Updated CONTRIBUTORS.md with username.
-
-
-
=> Logged in and Updated CONTRIBUTORS.md

CONTRIBUTORS.md
Issue: 1
Added my GitHub username to CONTRIBUTORS.md
Cloned & set the project up on my system. Signed up on PhotoStore and uploaded a picture.
Here's the screenshot:
=> Issue 1: Add adtoria to CONTRIBUTORS.md

CONTRIBUTORS.md
Issue: 1
Attached the screenshot after signup and added my username to contributors.md
-Added my username to Contributors.md
=> Added my username in the list

CONTRIBUTORS.md
Issue: 1
Set up a local clone of the project, added myself to CONTRIBUTORS.md and registered myself on localhost.
=> Added devmrfitz to CONTRIBUTORS.md

CONTRIBUTORS.md
Issue: 1
- Setup the project
- Signed up
- Added the name to Contributors.md
=> Signed up and added my username to Contributors.md

CONTRIBUTORS.md
Issue: 1
Short description of what this resolves:
Logged into website, created account, took screenshot, and updates CONTRIBUTORS.md
Changes proposed in this pull request and/or Screenshots of changes:
=> Added tushargupta9800

CONTRIBUTORS.md
Issue: 1
adding name in contibutor's list
=> Adding name in contributor.md

CONTRIBUTORS.md
=> Added my github username to contributors.md

CONTRIBUTORS.md
Issue: 1
- setup project on local machine
- added github username in contributers.md
=> adding github username in contributers.md

CONTRIBUTORS.md
Issue: 1
Setup the environment and added my name to contributors.md
=> Added username shlesh to contributors.md

CONTRIBUTORS.md
Issue: 1
Setting up the project in local Machine , done Sign up and added myself in contributors.md
=> Added me to contributors.md

CONTRIBUTORS.md
Issue: 1
Setup Project in local machine and update Contributors.md
=> Add batflarrow to contributiors.md

CONTRIBUTORS.md
Issue: 1
#1 
Updated name in Contributors.md and set project locally.
=> Modified Contributors.md

CONTRIBUTORS.md
Issue: 1
Added My Name to Contributors.md and Setup the project in my system
=> Added To Contributor And Setup

CONTRIBUTORS.md
Issue: 1
I have set up this project locally and also edited contributors.md
-
-
-
=> Project setup locally and contributors.txt edited

CONTRIBUTORS.md
Issue: 1 
added github in contributor.
=> added github in contributor

CONTRIBUTORS.md
Issue: 1
added GitHub username in CONTIBUTOR.md
=> Setting up the project #1

CONTRIBUTORS.md
Issue: 1
set up of project and added myself in contributors.md
-
-
-
=> added my name in contributors.md and set up of project

CONTRIBUTORS.md
Issue: 1
Added name in contributors.md
=> Issue: 1 added name in contributors.md
